Consumption Macro /!\ pb avec Git
klejim/Projet-tuteure-AS-INFO pull request #13
Opened 2018-04-07 13:51 UTC by Kennymkk

J'ai galéré avec git, j'ai recloné ton repo car j'arrivais pas à push sur celui que j'avais.

Ca a marché mais ça fout le boxon dans Network forcément, mais ça aurait été dans tous les cas non?
Normalement t'as besoin uniquement de Group et ConsumptionMacro

Dit moi ce que tu penses qui serait le mieux. Au pire je reclone ton projet et je remplace juste ConsumptionMacro et Group. Je ne sais pas ce qui le mieux, autant d'un point de vue pratique que propreté.
J'ai fait une manip pour changer le comment aie, je ne sais pas si ça vas prendre effet ici,d'après la manip ça a marché vus que je ne peux plus la faire.

2018-04-07 17:31 UTC, klejim requested changes
Je ne comprend pas ce que tu as fait avec c985daf. A la limite je te propose d'attendre lundi pour faire l'intégration, comme ça on pourra aussi revenir sur git.

Pour la suite je commente uniquement Group.java et ConsumptionMacro.java en partant du principe que toutes les autres modifications sont temporaires et causées par ce problème avec git.

2018-04-07 17:31 UTC, klejim commented on src/project/network/ConsumptionMacro.java
> +	public static HashMap<ConsumptionType,Double[]> consumpModes;
Tu as oublié de remplacer l'enum par un String comme on avait décidé de le faire. C'était pour permettre la création dynamique des modes de consommation depuis le fichier config.

Sinon je commence à me dire que des tableaux de tailles fixes limitent un peu nos options sur les modes de consommation qu'il sera possible de créer (par exemple si on veut un mode dont la période est différente de celle des autres, du genre pour un quartier spécial qui fonctionnerait un mois à fond et serait éteint l'autre mois). En même temps je réalise que c'est peut-être une considération inutile pour l'instant, donc autant ne pas agir là-dessus avant d'avoir un vrai objectif en tête.

2018-04-07 17:31 UTC, klejim commented on src/project/network/ConsumptionMacro.java
> +			System.err.println("Erreur assignation tab Consommation mauvaise taille");
Quand tu détectes un problème tu devrais retourner une valeur ou lever une exception, ça permet de gérer l'erreur au niveau du code utilisant la fonction. En l'état tu as une fonction qui a un comportement "normal" et un autre très différent et tu n'as aucun moyen de savoir dans quel cas tu te trouves.

2018-04-07 17:31 UTC, klejim commented on src/project/network/ConsumptionMacro.java
> +	}
Je lui aurais donné un nom différent du getter de base pour mieux les différencier mais c'est peut-être seulement moi.

2018-04-07 17:31 UTC, klejim commented on src/project/network/Group.java
> +    	}
Je crois que tu utilises la mauvaise méthode. Si je ne me trompes pas cette ligne devrait être 
```java
return (int) (ConsumptionMacro.getConsumFactor(this.consumpType, ahead_Ite)*this.originalconsumption);
```
ce qui utiliserait la méthode renvoyant la consommation future plutôt que celle donnant la consommation actuelle.

2018-04-07 17:31 UTC, klejim commented on src/project/network/Group.java
> +    }
Et du coup comme j'avais dit dans #9 je propose de considérer qu'un groupe doit obligatoirement suivre un mode de consommation et de supprimer l'ancien constructeur. Cela permettrait aussi de ne pas avoir à vérifier l'existence de `consumpType` dans `update()`.

2018-04-07 20:25 UTC, Kennymkk commented
C'était surtout pour voir si y'avait pas de souci majeur avec la manip github

Du coup y'a eu au moins un problème (surement avant) parce que j'avais supprimé ConsumptionType

2018-04-07 20:26 UTC, Kennymkk commented on src/project/network/Group.java
> +    }
oki

2018-04-07 20:28 UTC, Kennymkk commented on src/project/network/ConsumptionMacro.java
> +			System.err.println("Erreur assignation tab Consommation mauvaise taille");
Comme tu veux de toute façon ça ne devrait plus arriver, je suis pas sur que lever une exception soit le bon choix sauf si consumption n'est setté que ici.

2018-04-08 10:22 UTC, Kennymkk commented
Après avoir appris Github "the hard way", je penses que ce commit est OP dans le sens où y'a pas d'erreur lié à la manip git.
Je sais pas pourquoi il a ajouté les lignes sur le configparser, j'y ai pas "réellement" touché.

2018-04-08 11:16 UTC, klejim requested changes
Ce n'est pas très grave pour ConfigParser, je l'ignorerai en mergant.

2018-04-08 11:16 UTC, klejim commented on src/project/network/ConsumptionMacro.java
> +			return 1;
J'ai du mal à voir ce que tu veux faire. Si tu veux prendre en compte le cas où consumpTab est nul est-ce que ça ne devrait pas être `if (consumpTab != null && consumpTab.length == tabSize)` ?

D'ailleurs si tu voulais aller jusqu'au bout dans la vérification tu devrais vérifier que le tableau existe et est rempli, c'est-à-dire qu'il n'existe aucun élément de consumpTab tels que `consumpTab[i] == null` vaut `true`. Je ne sais pas s'il est nécessaire d'aller aussi loin.

2018-04-08 11:16 UTC, klejim commented on src/project/network/ConsumptionType.java
> +}
Tu peux supprimer un fichier de ton repo en faisant `git rm <fichier>`.

2018-04-08 11:16 UTC, klejim commented on src/project/network/Group.java
> +    public void updateConsumption(){
Je crois qu'elle l'est oui. Tu peux la supprimer si tu veux.

2018-04-08 11:16 UTC, klejim commented on src/project/network/Group.java
> +    	if(this.consumpType!=null) {
Maintenant que les groupes sont nécessairement créés avec un consumpType ce test est inutile.

2018-04-08 12:18 UTC, Kennymkk commented on src/project/network/Group.java
> +    	if(this.consumpType!=null) {
Je sais mais autant laisser au cas où pour le futur non? ça mange pas trop de pain.

2018-04-08 12:50 UTC, klejim commented on src/project/network/Group.java
> +    	if(this.consumpType!=null) {
Si tu y tiens pourquoi pas.

2018-04-08 12:53 UTC, klejim commented
Du coup tout sera ok de mon côté dès que tu auras corrigé ce test dans `ConsumptionMacro.setConsumpTab()` et ajouté la javadoc.

A priori ça devrait marcher mais par acquis de conscience tu as testé ces changements ou pas ?

2018-04-08 16:53 UTC, Kennymkk commented
J'aurais du retesté getFutureConsumption sous ta version de Network et Test, en fait son fonctionnement dépends de où on l'appelle, c'est à dire avant ou après le network runOnce( ) , sous ta version appelé dans la vue il décale de 1 de trop.
On discutera de ça demain, si tu appelles runOnce ( ) en premier dans la boucle et que tu ne compte pas l'utiliser dans runOnce( ) tout devrait bien se passer en mettant juste un -1 (je te le commit après) sinon il faudra mettre un warning dans la javadoc ou autre.

2018-04-08 17:11 UTC, klejim reviewed
`getFutureConsumption()` sera appelé _dans_ `runOnce()` en fait. La méthode doit donner la consommation du groupe à partir de l'itération considérée dans `analyze()` et `handleErrors()` (donc faire getFutureConsumption(1) doit donner la consommation normale du groupe lors du prochain appel à runOnce).

2018-04-08 17:11 UTC, klejim commented on src/project/network/ConsumptionMacro.java
> +			consumpModes.put(consumpType, consumpTab);
Il te faut inverser les deux conditions sinon ce code va lever une `NullPointerException` si consumpTab est `null`.

2018-04-08 17:13 UTC, Kennymkk commented
et uniquement dans runOnce?

2018-04-08 17:30 UTC, klejim commented
Probablement. En tous cas c'est la fonction qui décrit une itération du réseau donc c'est là qu'on en aura principalement besoin.

Après je suis d'accord que nous allons devoir nous poser la question de quand faire progresser le réseau d'une itération et de comment récupérer tout ce qu'on veut dans la vue de manière à ce que ce soit cohérent avec l'affichage courant (par exemple comment récupérer une estimation de la consommation future qui n'est pas décalée d'une itération).

2018-04-14 13:29 UTC, Kennymkk commented
Normalement je suis prêt pour le commit. Si tu vois ce message 15 minutes après être posté attends un peu je regarde les changements sur git pour m'assurer que y'ai aucun souci.

Y'a un truc dont y faut qu'on parle dans Consumption macro : la différence entre _GetConsumFactor(String)_ et _GetConsumFactor(String,int aheadIte)_ . Je voulais faire qu'une seule fonction mais avec la façon dont est architecturé le code appeller cette fonction avec 0 dans le runOnce() n'est pas bon, il faudrait l'appeller avec 1 pour l'actuel, et dans la vue il faudrait l'appeller avec 1 pour avoir la prochaine. Ce n'est donc pas très cohérent, donc la version avec juste le String sert à la fonction _update_  pour le moment
Si c'est le seul souci j'aimerais bien que tu intégres quand même, parce que cela dépends de comment le code se déroulera dans TEST et dans Network, et il se peut que la solution d'avoir 2 fonctions soit la meilleure et les autres ne devraient pas changer le code.

Egalement dans la version _GetConsumFactor(String,int aheadIte)_ j'ai mis un try/catch pour le ArrayOutoFBONDS, tu me diras si tu es d'accord avec la méthode, le code continuerait de tourner en allant chercher la consommation actuelle et donnerait un message d'erreur. Ou sinon je peux le faire crasher, je ne sais pas ce qui est le mieux.

2018-04-14 13:49 UTC, Kennymkk commented
J'ai essayé de voir la cause du PowerIn mais je suis pas certain que ça vienne de mon coté, je n'ai pas touché à SubStation normalement, tu n'as jamais eu ce problème à un point dans ton dévellopement?

Là pour le fixer je devrais toucher à des choses auxquelles je ne devrais pas et auxquelles je n'ai pas touché normalement.

2018-04-14 17:12 UTC, klejim commented
Il  n'y a plus de runOnce dans master, je l'ai éclatée en une méthode update et les deux autres d'analyse et de gestion en début de semaine (après qu'on en ait parlé donc). Je verrai ce que j'en ferai.

Quand tu dis que PowerIn est décalée tu parles de quoi exactement ? C'est en avance, en retard, et surtout c'est où?

2018-04-14 18:10 UTC, Kennymkk commented
En retard de une période, le PowerIN des SousStations qui s'affiche par la vue

2018-04-14 18:13 UTC, klejim reviewed
Quelques remarques plus ou moins mineures. En plus de ce qui suit je pense que tu devrais mieux commenter la logique de tes classes. Je sais que tu veux attendre d'être sûr qu'un truc est finalisé pour le documenter mais expliquer comment fonctionne telle classe et sa place dans l'évolution du modèle est utile avant cette étape de finalisation (au moins pour les autres qui regardent ton code). 

L'idée est vraiment d'avoir dans le code un résumé des explications que tu donnes quand on en parle, par exemple si tu regardes mes méthodes et classes dès que je fais un truc non trivial j'essaie d'expliquer la logique.

2018-04-14 18:13 UTC, klejim commented on src/project/network/ConsumptionMacro.java
> +	private static boolean RANDOM_ON;
On en a déjà parlé mais cinq lignes avant et après la déclaration c'est peut-être un peu trop. ;)

2018-04-14 18:13 UTC, klejim commented on src/project/network/ConsumptionMacro.java
> +		catch(ArrayIndexOutOfBoundsException e){
Je serais plus pour virer le -1 et gérer un éventuel décalage au niveau de l'appel de la fonction.

2018-04-14 18:13 UTC, klejim commented on src/project/network/RandomMacro.java
> +public class RandomMacro extends ConsumptionMacro {
Tu es sûr de toi pour l'extends? C'est un peu étrange sachant que tu utilises RandomMacro dans ConsumpMacro et que cette dernière ne possède que des membres statiques (c'est-à-dire que tout ce que tu avais dans ConsumpMacro va se retrouver dans RandomMacro). En fait je ne vois pas vraiment pourquoi créer ce lien entre les deux classes.

2018-04-14 18:14 UTC, klejim commented
Pour le retard de PowerIn j'ai réglé ça dans le dernier commit de master.

2018-04-14 18:22 UTC, Kennymkk commented
Ah super!
Comme convenu _ConsumptionMacro_ et les interactions qui y sont liés sont normalement toutes propre, et la classe Random qui n'est pas si mal non plus est proprement désactivée et donc ne devrait pas interférer avec le reste du modéle.

J'ai encore relu un peu, je pense que ça devrait être bon pour le merge, tu vas avoir le temps?

2018-04-14 18:25 UTC, Kennymkk commented on src/project/network/RandomMacro.java
> +public class RandomMacro extends ConsumptionMacro {
Non j'en suis pas du tout sur , c'est plus symbolique de toute façon,et il n'y a pas de méthode hérité ça ne change pas grand chose, je supprime.

2018-04-14 18:26 UTC, Kennymkk commented on src/project/network/ConsumptionMacro.java
> +	private static boolean RANDOM_ON;
D'accord

2018-04-14 18:26 UTC, Kennymkk commented on src/project/network/ConsumptionMacro.java
> +	private static boolean RANDOM_ON;
oui



D'accord



Je l’enlève

2018-04-14 18:27 UTC, Kennymkk commented on src/project/network/ConsumptionMacro.java
> +		catch(ArrayIndexOutOfBoundsException e){
Dans la fonction de Group tu veux dire?

Après le try catch ça protége contre les valeurs négatives qui peuvent aussi venir de ahead_ite, mais je peux le rendre unsigned aussi

2018-04-14 18:43 UTC, Kennymkk commented
Oui tu as raisons pour la docu aussi j'ai vus ce point en dernier.
Là je suis un peu fatigué pour faire RandomMacro mais j'ai fait la docu ConsumptionMacro

2018-04-14 18:58 UTC, klejim commented on src/project/network/ConsumptionMacro.java
> +		catch(ArrayIndexOutOfBoundsException e){
Les types unsigned n'existent pas en java.

Laisse-le comme ça sinon, au pire je l'ajusterai si ça devient nécessaire.

2018-04-14 19:06 UTC, klejim commented
Ce n'est pas très grave pour RandomMacro, ça peut attendre que tu l'active.

Je vais essayer de tester et de faire le merge ce soir. Sinon je pars demain donc je le ferai quand je pourrais.

2018-04-14 19:51 UTC, Kennymkk commented
T'embêtes pas trop au pire en vrai je mergerai sur ma branche

2018-04-14 20:02 UTC, klejim commented
J'attends que tu me dises avoir terminé alors.

2018-04-14 20:12 UTC, Kennymkk commented
Moi  en vrai je crois que c'est terminé.
Je voulais dire au pire j'essayerais de prendre ton dernier commit et de le merge sur ma branche

2018-04-14 20:17 UTC, klejim commented
Je voulais dire que tu aie terminé le merge puisque tu proposais de le faire.

Tu le fais où je le fais du coup?

2018-04-26 00:37 UTC, merged