Merge RandomMacro (activée!)
klejim/Projet-tuteure-AS-INFO pull request #19
Opened 2018-05-08 16:13 UTC by Kennymkk

Voilà

J'ai séparé l'initialisation dans ConsumptionMacro, mais du coup il y a 2 fonctions d'initialisation, une pour les fonctions qui ont besoins du Network, et l'autre non.

Je peux faire autrement mais il faut alors changer l'éxécution du code dans Network pour que le réseau soit crée lors de l'assignation du tableau de consommation.

Dans RandomMacro si je fais de même je ne peux plus mettre les valeurs de randomisation en final, donc c'est comme tu veux ça reste à débattre ces valeurs pourraient être intégré dans le parser. Ou pas.

2018-05-08 22:23 UTC, klejim requested changes
Comme toujours j'ai quelques remarques, mais tu as l'habitude maintenant. ;)

Le facteur aléatoire varie dans quelle plage de valeur?

2018-05-08 22:23 UTC, klejim commented on src/project/network/ConsumptionMacro.java
>  		ConsumptionMacro.tabSize = tabSize;
Donner la possibilité de changer la taille de tableaux (et donc la "période" du réseau) peut être bien mais il faut que ce soit complètement supporté.

Par exemple que fait-on des tableaux déjà définis? Se contenter de modifier `tabsize` fera planter le réseau si un groupe suit un des anciens modèles de consommation.

2018-05-08 22:23 UTC, klejim commented on src/project/network/ConsumptionMacro.java
>  		if (consumpTab.length == tabSize && consumpTab != null) {
Ce test lève une NullPointerException si consumpTab est null.

2018-05-08 22:23 UTC, klejim commented on src/project/network/ConsumptionMacro.java
> +		}
Toujours pour éviter une exception tu devrais tester le cas où consumpTab est null avant de t'intéresser à sa longueur.

2018-05-08 22:23 UTC, klejim commented on src/project/network/RandomMacro.java
> +	 */
Je me demande si ça vaut le coup de définir le cluster auquel un groupe appartient dans le fichier network plutôt que faire un ClusterGroup par sous-station. Ce serait moins rigide, mais c'est seulement une idée.

2018-05-09 08:05 UTC, Kennymkk commented on src/project/network/RandomMacro.java
> +	 */
ah oui, ça me semblait juste le plus pertinent pour tester rapidement tester des situations intéréssantes pour l'algo (fort taux aléatoire sur les groupes d'une ss-station => les centrales liés sont en difficultés). Mais effectivement c'est une solution plus propre.

2018-05-10 12:45 UTC, Kennymkk commented
Les premiers points sont réglés, je suis en train de faire le configparser.
Il faudrait qu'on se mette d'accord sur quelques points pour que je puisse l'implémenter :

~~1) Je rajoute une ArrayList des Clusters à Network. Je pourrais peut-être en faire une extends node, mais j'aime pas trop l'idée, parce que ce n'est pas réelement une node.~~


2) Je rajoute un champ id sur mes ClusterGroup. Ainsi dans le fichier config, on spécifiera l'id pour chaque group mais cela pose quelques problèmes dont les solutions devront être testés :
 je dois du coup rajouter un constructeur avec une id, vérifier que cette id n'existe pas déjà, de même pour le constructeur avec l'id qui s'incrémente automatiquement. OU mettre en pré-requis du fichier network que les id de cluster doivent être consécutives (0,1,2,3) et faire crasher le cas échéant. 

edit : Si tu es d'accord avec le dernier commit considère peut-être de le merger parce que le prochain sera bien plus gros. (en même temps celui là est très petit)

Je pense je vais essayer de finir l'intégration du parser au passage.

2018-05-10 13:52 UTC, Kennymkk commented
Regardes le dernier commit voir si tu es d'accord avec la manière dont je réalise l'intégration du parser.

2018-05-10 15:07 UTC, klejim commented
Au niveau du fichier network les sous-stations déclarent deux tableaux d'objets correspondants aux groupes et centrales auxquelles elles sont liées. Par exemple : 
```
### SUBSTATION_1 ###
name = "station 1";
groups = {GROUP_1, GROUP_2};
plants = {PLANT_1};
```
 
GROUP_1, GROUP_2 et PLANT_1 sont des identifiants d'éléments définis ailleurs dans le fichier et la structure {id1,id2} est reconnue par le parser comme étant un "tableau d'objets", mais réellement c'est un ArrayList de String qui est créé et stocké dans la map aux clés "plants" et "groups". 

Après pour l'analyse de cette map en vue de créer le réseau je n'avais rien de fixé (d'ailleurs ce qui précède peut être changé si tu as une meilleure idée, mais j'aime l'idée de simplifier au maximum la syntaxe du fichier network), donc tu fais un peu comme tu veux.

Je regarde ton code dès que j'ai plus temps.

2018-05-10 15:11 UTC, Kennymkk commented
Donc si jet get la key groups je dois le faire dans un ArrayList de String?
Après je dois aller chercher les nodes correspondantes dans network.nodes par le nom ou tu as déjà prévu quelques chose?

2018-05-10 15:37 UTC, klejim commented
La valeur de groups est bien une instance d'ArrayList<String>, oui (idem pour plants).

Je n'ai rien prévu pour la suite. Si je devais le faire je bouclerais sur les clés en initialisant les centrales, groupes et sous-station rencontrés et en stockant les ids des centrales et des groupes (je parle de leurs clés) afin de pouvoir les associer plus tard aux éléments créés. Je stockerais les sous-stations dans une structure à part pour pouvoir y revenir dessus lorsque tous les groupes/centrales ont été créés afin de terminer leur initialisation.

Mais c'est très général et juste une idée pour ne pas te laisser en mode "débrouille toi", tu peux absolument faire autrement.

2018-05-10 15:39 UTC, klejim commented
Par contre la création du réseau diverge un peu du but originel de cette pull request. Il aurait été mieux que tu le fasses dans une branche à part, mais ce n'est pas trop grave.

2018-05-10 17:01 UTC, klejim commented
Et c'est seulement maintenant que je me rend compte que ta PR vise master plutôt que jalon2. Je vais la fermer, tu devras en refaire une vers jalon2 (idéalement en séparant randomisation et création du réseau si ça peut se faire facilement, sinon tant pis).

2018-05-10 17:01 UTC, closed without merging