Make ihm texte
klejim/Projet-tuteure-AS-INFO pull request #8
Opened 2018-03-31 06:40 UTC by yo55

L'IHM texte à merger (ou pas) dans master, il ne devrait pas y avoir de conflits.

2018-03-31 09:47 UTC, klejim commented
Tout à l'air bien mais le seul moyen de lancer l'application est de faire appel au main de StatusWindow qui est une fonction de test. Est-ce que tu pourrais ajouter un point d'entrée qui ferait appel à createView et aurait un comportement plus générique ? Ce serait plus propre.
- [ ] créer un point d'entrée qui n'effectue pas de tests

2018-03-31 23:02 UTC, klejim requested changes
- [ ] créer un point d'entrée qui n'effectue pas de tests

(je découvre que je peux faire ça, c'est cool)

2018-04-02 13:31 UTC, yo55 commented
Ok. Pour le lancement, il y a trois fonctions dans la classe View qui permettent de créer/mettre à jour/supprimer la fenêtre à partir d'un objet réseau. Je m’aperçois cependant que j'ai oublié de créer un constructeur pour  View. Je corrige tout ça.

2018-04-02 20:26 UTC, yo55 reviewed
j'ai ajouté un constructeur à la classe View qui créé la StatusWindow. Les méthodes de classe View.updateView() et View.deleteView() permettent respectivement de mettre à jour et supprimer la fenêtre

2018-04-02 20:34 UTC, klejim commented
Super, je merge ça.

2018-04-02 20:42 UTC, klejim approved these changes

2018-04-02 20:42 UTC, merged

2018-04-02 21:05 UTC, klejim commented
Au temps pour moi, il y a un problème.

L'IHM était parfaitement fonctionnelle avec l'ancienne architecture mais les changements apportés par #10  font qu'elle affiche désormais des résultats semi-incohérents et surtout faux. C'est entièrement ma faute pour avoir changé l'archi sans te prévenir et pour ne pas avoir pensé que ça allait poser problème. 

J'ai annulé le merge en attendant qu'on en parle.